apiVersion: v1
kind: Service
metadata:
  name: postgres-primary-service
spec:
  selector:
    app: postgres
    role: primary
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP