spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/service-1-db}
    username: ${DB_USERNAME:smartsense}
    password: ${DB_PASSWORD:smartsense}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:8080}